#!/bin/python
import serial
import os
import time
 
s=serial.Serial(port='/dev/ttyUSB0',baudrate=9600,timeout=1)

time.sleep(0.2) # wait 2ms
s.flushInput()
s.flushOutput()

time.sleep(0.2) 
s.write('GET STATUS\r\n')

time.sleep(0.2)
status=s.readlines()
print "%s" % status[-1].strip()
